services:
  ruoyi-nacos:
    container_name: ruoyi-nacos
    image: nacos/nacos-server:v2.2.0
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - DB_NUM=1
      - DB_URL_0=jdbc:mysql://ruoyi-mysql:3306/ry-config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USER=root
      - DB_PASSWORD=rn@123456
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - ruoyi-mysql
    restart: always

  ruoyi-mysql:
    container_name: ruoyi-mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower-case-table-names=1
    environment:
      MYSQL_ROOT_PASSWORD: rn@123456
      MYSQL_DATABASE: ry-cloud
    restart: always

  ruoyi-redis:
    container_name: ruoyi-redis
    image: redis
    ports:
      - "6379:6379"
    restart: always

  ruoyi-nginx:
    container_name: ruoyi-nginx
    image: nginx
    ports:
      - "80:80"
    restart: always

  ruoyi-gateway:
    container_name: ruoyi-gateway
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - ruoyi-redis
      - ruoyi-nacos
    restart: always

  ruoyi-auth:
    container_name: ruoyi-auth
    build:
      context: ./auth
    depends_on:
      - ruoyi-redis
      - ruoyi-nacos
    restart: always

  ruoyi-system:
    container_name: ruoyi-system
    build:
      context: ./system
    depends_on:
      - ruoyi-redis
      - ruoyi-mysql
      - ruoyi-nacos
    restart: always

  ruoyi-gen:
    container_name: ruoyi-gen
    build:
      context: ./gen
    depends_on:
      - ruoyi-mysql
      - ruoyi-nacos
    restart: always

  ruoyi-job:
    container_name: ruoyi-job
    build:
      context: ./job
    depends_on:
      - ruoyi-mysql
      - ruoyi-nacos
    restart: always

  ruoyi-file:
    container_name: ruoyi-file
    build:
      context: ./file
    restart: always
